### ISSUE TITLE
head.cow does not reset term properly

### ISSUE THREAD

**Issue by donaldducky** [paulkaefer/cowsay-files#14]
I was checking out all the cowsay files and noticed the text came out black part way through.

Using something like this:
`fd . -tf | sed 's/\.cow$//' | while read i; do echo "$i" | cowsay -f "$i"; done`

I've narrowed it down to `head.cow`.

I can reproduce the issue by running this command: `echo "Hello" | cowsay -f head; echo "hi"`

![Screen Shot 2019-09-24 at 10 08 23 AM](https://user-images.githubusercontent.com/249234/65519078-65cda900-deb3-11e9-9bb3-cf54e3ab1591.png)

Notice the hi at the end is black.

Not sure what the issue is after glancing at the file but it starts after the second line of the cow.

**Comment by roguepullrequest** [comment]
Can confirm that this does bork a terminal. No idea as to why but is totally a thing to watch out for.

**Comment by paulkaefer** [comment]
@donaldducky I suspect [this](https://github.com/paulkaefer/cowsay-files/commit/55c789eaf79c9b8da31a98ab0ae8ca2aaba69ab8) was the issue. Can you confirm?

cc: @roguepullrequest

**Comment by donaldducky** [comment]
Hi @paulkaefer tried it out and it still produces the same result 😢

**Comment by paulkaefer** [comment]
@donaldducky after the black "hi" in your screenshot, does the terminal prompt return to normal?

What shell are you running?

**Comment by donaldducky** [comment]
My prompt was also going back to normal, just the "hi" was still black.

My understanding is that it should go back to normal after cowsay exits.

Like this:
<img width="565" alt="hi" src="https://user-images.githubusercontent.com/249234/72621506-5fa28300-390f-11ea-8b10-ea893a92d096.png">

Using `zsh`.

**Comment by paulkaefer** [comment]
I hadn't realized you were printing something on the same line. This is because the color was not reset within the cow file itself. See 88b2f7e.
