### ISSUE TITLE
"-tc" or "true-color/" for 24-bit true-color cows?

### ISSUE THREAD

**Issue by apjanke** [paulkaefer/cowsay-files#24]
The README says "True color (ending in '-tc') cows...", but I don't see any cow files here with a `-tc` suffix in their names. There's a `cows/true-color/` subdirectory, though. Should the readme be updated to reflect this different convention?

```
[cows] $ pwd
/Users/janke/local/repos/cowsay-files/cows
[cows] $ ls *-tc*
gls: cannot access '*-tc*': No such file or directory
[cows] $ ls */*-tc*
gls: cannot access '*/*-tc*': No such file or directory
[cows] $
[cows] $ cowsay -f elaine boo
cowsay: Could not find elaine cowfile!
[cows] $ cowsay -f elaine-tc boo
cowsay: Could not find elaine-tc cowfile!
[cows] $ cowsay -f true-color/elaine boo
 _____
< boo >
 -----
[cows] $
```

Same with the `list-ascii-cows.sh` script. It seems to be checking for a `-tc` suffix, but it doesn't find any of them. Should it be looking under `cows/true-color` instead?

**Comment by paulkaefer** [comment]
Good call. Do you want to put in the fix?

**Comment by apjanke** [comment]
Sure.

Ah, I see something: the files in `converter/src_images` do have `-tc` suffixes in some of them. And list-ascii-cows.sh isn't handling that right.

What exactly is `list-ascii-cows.sh` supposed to do? Does it list all the cow files which are _not_ sourced from one of the converter images?

**Comment by paulkaefer** [comment]
Yeah. When I first started this, I preferred the cows to just be ASCII. But we've had some nice contributions of Unicode cows, so this was an attempt to be able to list the ASCII ones in case you only wanted to use those.

**Comment by apjanke** [comment]
Cool. Here's a PR: #25.
