### ISSUE TITLE
Install Script?

### ISSUE THREAD

**Issue by RandoNandoz** [paulkaefer/cowsay-files#29]
I'd be glad to contribute an install script.

**Comment by paulkaefer** [comment]
We already have one... https://github.com/paulkaefer/cowsay-files#installation.

I'll leave this open if you had some other idea (I suppose you could write a script that clones the repo and copies it to the cowfile path... and maybe a `curl` one-liner to pull the script and run it?)

**Comment by paulkaefer** [comment]
@RandoNandoz I'm closing this as "unnecessary" since the basic idea is:
1. have `cowsay` installed
2. copy any/all cowfiles you want

If you have additional thoughts, feel free to comment, or open a PR!
