### ISSUE TITLE
too huge images

### ISSUE THREAD

**Issue by rtng** [paulkaefer/cowsay-files#31]
hello, 
this is a very nice piece of art :) , and i don't even know if this is an issue actually, but the size of the images are too huge on my terminal/console. It seems that the single (pixel/dots or how it's been called) are not conform to my char size ... .
Any suggestion how i might be able to fix this.
Thank you a lot!

**Comment by paulkaefer** [comment]
You're right that this is not an issue impacting this repository, so I'm closing it.

It totally depends on your setup & I'm not sure how much help I'll be even if additional details are provided. You're welcome to post those details, and please include which cow file and a screenshot of the output.
