### ISSUE TITLE
[Git Repo] Homebrew formula cannot git clone as HEAD points to master and not the main branch

### ISSUE THREAD

**Issue by andrewcrook** [paulkaefer/cowsay-files#32]
Homebrew formula fails to clone this repo

Installing cowsay-files
the git clone fails it still looks for the master branch when the cow-files repo has been changed to main

```
fatal: Remote branch master not found in upstream origin
Error: cowsay-files: Failed to download resource "cowsay-files”
```
Can you please change the repo HEAD to point to main please?

[/cowsay-org/homebrew-cowsay/Formula/cowsay-files.rb](https://github.com/cowsay-org/homebrew-cowsay/blob/c3e946c6640e5e1977f32dcb0c6d0bed64ee8214/Formula/cowsay-files.rb#L5)

<img width="360" alt="image" src="https://github.com/paulkaefer/cowsay-files/assets/803618/86aa1066-9644-439d-8515-743697359528">

**Comment by andrewcrook** [comment]
@paulkaefer 

No I think something is wrong with paulkaefer/cowsay-files this repo if the default branch is main the HEAD ref should be the same and its not its still master which is github's old default branch.

hope this helps

```
==> Cloning https://github.com/paulkaefer/cowsay-files.git
Cloning into '/Users/andrew/Library/Caches/Homebrew/cowsay-files--git'...
fatal: Remote branch master not found in upstream origin
Error: cowsay-files: Failed to download resource "cowsay-files"
Failure while executing; `/usr/bin/env git clone --branch master --config advice.detachedHead=false --config core.fsmonitor=false https://github.com/paulkaefer/cowsay-files.git /Users/andrew/Library/Caches/Homebrew/cowsay-files--git` exited with 128. Here's the output:
Cloning into '/Users/andrew/Library/Caches/Homebrew/cowsay-files--git'...
fatal: Remote branch master not found in upstream origin
```

**Comment by paulkaefer** [comment]
@andrewcrook the default branch here is `main`. I see `--branch master` in your code snippet, so there must be somewhere that is assuming `master` is the default branch.
![Screenshot 2023-09-11 at 1 33 29 PM](https://github.com/paulkaefer/cowsay-files/assets/2408155/28775a5d-15ae-480f-896c-2e605f31401d)

**Comment by paulkaefer** [comment]
@andrewcrook a quick skim of https://docs.brew.sh/Formula-Cookbook suggests there are ways to specify which branch the homebrew formula uses. Please open an issue or PR in https://github.com/cowsay-org/homebrew-cowsay!

**Comment by apjanke** [comment]
Yep, I'm the right contact for @cowsay-org and that https://github.com/cowsay-org/homebrew-cowsay repo. Thanks for the referral here.

Merged a fix for this from https://github.com/cowsay-org/homebrew-cowsay/pull/1, using andrewcrook's fix. Looks to me like Homebrew's `brew` tool assumes that the default branch for "HEAD" formula's source repos is "master" and can't handle a default branch named "main", even though that's common these days. (Or maybe my original formula was obsolete in some way.)

Thanks, y'all!
